name: JavaDoc Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      #Build with java 21
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6
    - name: Set up JDK 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 #v4.2.1
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -Pjavadoc-check -B package --file pom.xml
