name: License Header Check

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Check License Header
        uses: apache/skywalking-eyes@cd7b195c51fd3d6ad52afceb760719ddc6b3ee91 # v0.6.0
        env:
            GITHUB_TOKEN: ${{ secrets.DASH_IPLAB_TOKEN }}  # needed only when you want License-Eye to comment on the pull request.
