name: Deploy Maven

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    if: ${{ (github.repository == 'eclipse-daanse/org.eclipse.daanse.rolap.model') && (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.ORG_GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Set up Java for publishing to Maven Central Snapshot Repository
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: PASSPHRASE
      - name: deploy
        run: mvn -Pdeploy --no-transfer-progress --batch-mode clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.ORG_OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ORG_OSSRH_PASSWORD }}
          PASSPHRASE: ${{ secrets.ORG_GPG_PASSPHRASE }}

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        continue-on-error: true
        uses: advanced-security/maven-dependency-submission-action@5d0f9011b55d6268922128af45275986303459c3 # v4.0.3
        with:
          directory: '/'
